server:
  port: 8090
grpc:
  client:
    srv:
      address: 'static://localhost:50051'
      negotiationtype: plaintext
      max-inbound-message-size: 1GB
      enable-keep-alive: true
      keep-alive-time: 30s
      keep-alive-timeout: 30s
